version: '3.8'

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    depends_on:
      - postgres-db
    environment:
      - PORT=${PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=postgres-db
      - DB_DIALECT=postgres
    ports:
      - "5000:5000"
    command: ["sh", "-c", "sleep 5 && node server.js"]

volumes:
  pgdata:
